# Copyright (c) 2018 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

services:
  - docker

before_install:
  - docker pull shapelets/khiva
  - docker run -i -t -d --name CI shapelets/khiva-r
  - docker exec -it CI /bin/bash -c "mkdir -p /home/travis/build/shapelets/khiva-r"
  - docker cp . CI:/home/travis/build/shapelets/khiva-r

install:
  - |
    docker exec -it CI /bin/bash -c "cd /home/travis/build/shapelets/khiva-r; \
    apt-get update; apt-get install libxml2-dev libxslt-dev -y; Rscript .CI/travis/install.R"


script:
  - docker exec -it CI /bin/bash -c "cd /home/travis/build/shapelets/khiva-r; Rscript .CI/travis/script.R"
  - docker exec -it CI /bin/bash -c "cd /home/travis/build/shapelets/khiva-r; mv ./cobertura.xml ./coverage.xml"

after_success:
  - docker cp CI:/home/travis/build/shapelets/khiva-r/coverage.xml .
  - bash <(curl -s https://codecov.io/bash)
